name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 23.x]

    defaults:
      run:
        working-directory: ./Frontend

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./Frontend/package-lock.json # Ensure this path is correct

      - name: Install dependencies (in Frontend directory)
        run: npm ci

      - name: Run linting (in Frontend directory)
        run: npm run lint

      - name: Build Next.js app (in Frontend directory)
        run: npm run build

      - name: Start Next.js server (in Frontend directory)
        run: npm run start & # Start in background
        env:
          PORT: 3000

      - name: Wait for Next.js Server
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: curl --fail http://localhost:3000 #check if server has properly started.

      - name: Upload test reports (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: ./Frontend/coverage # Ensure this path is correct
